MP-156 ендпоіти для взаємодії із чатами і повідомленнями
LionnoiL/petmarket pull request #134
Opened 2024-05-12 09:18 UTC by KovalBohdan-0

Додав ендпоінти для взаємодії із чатами та повідомленнями

Message ендпоінти - 
DELETE/v1/messages/{id} Видалення повідомлень за id (юзер може видалити тільки свої повідомлення)
POST/v1/messages Додавання повідомлень (не можна додати повідомлення, якщо юзер в чорному списку в користувача до якого він хоче написати)
PUT/v1/messages/{id} Зміна повідомлення за id
PUT/v1/messages/{id}/read Прочитання повідомлення за id

Chat ендпоінти -
GET/v1/chat Діставання всіх чатів цього юзера (не включаються чати з юзерами в чорному списку)
GET/v1/chat/{chatUserId} Діставання чату за id
PUT/v1/chat/{chatUserId}/read Прочитання всіх повідомлень в чаті

2024-05-12 17:24 UTC, LionnoiL requested changes

2024-05-12 17:24 UTC, LionnoiL commented on src/main/java/org/petmarket/message/controller/MessageController.java
> +
юзер з id 1 може написати повідомлення юзеру з id 1. це баг чи фіча?

2024-05-12 17:24 UTC, LionnoiL commented on src/main/java/org/petmarket/message/repository/MessageRepository.java
> +}
монструозно :-). сам писав?

2024-05-12 17:24 UTC, LionnoiL commented on src/main/java/org/petmarket/message/service/MessageAccessCheckerService.java
> +    }
можеш своїми словами написати що робить ця перевірка? хто тут може не мати доступ? з дороги голова не варить. це тіпа первіряємо що передали id поточного юзера якщо він не адмін? а якщо адмін то можемо створити повідомлення "від імені" будь якого користувача?

2024-05-12 17:24 UTC, LionnoiL commented on src/main/java/org/petmarket/message/service/MessageAccessCheckerService.java
> +    }
author_id обов'язково передавати з фронту? не можна отримати його через getCurrentUser?

2024-05-12 18:26 UTC, KovalBohdan-0 commented on src/main/java/org/petmarket/message/service/MessageAccessCheckerService.java
> +    }
ну я ніби зробив щоб адмін міг завжди надсилати повідомлення, можливо це зайве, якщо так то впринципі можна зробити через getCurrentUser

2024-05-12 18:27 UTC, KovalBohdan-0 commented on src/main/java/org/petmarket/message/repository/MessageRepository.java
> +}
пробував зробити якось по простіше, але це найкраще що вийшло

2024-05-12 18:29 UTC, KovalBohdan-0 commented on src/main/java/org/petmarket/message/controller/MessageController.java
> +
тут запитання чи нам це потрібно, думаю можна забрати таку можливість, бо в нас все-таки не месенджер

2024-05-12 18:37 UTC, KovalBohdan-0 commented on src/main/java/org/petmarket/message/controller/ChatController.java
> +        return messageService.getLatestChats(PageRequest.of(page - 1, size));
але по ідеї тут вроді немає бути ніколи forbidden, бо юзер по ідеї завжди може взяти свої повідомлення, бо воно працює через getCurrentUserId

2024-05-12 18:37 UTC, KovalBohdan-0 commented on src/main/java/org/petmarket/message/controller/ChatController.java
> +    }
тут також по ідеї немає ніколи бути 403

2024-05-13 05:08 UTC, LionnoiL commented on src/main/java/org/petmarket/message/controller/ChatController.java
> +        return messageService.getLatestChats(PageRequest.of(page - 1, size));
точно. туплю.

2024-05-13 05:09 UTC, LionnoiL commented on src/main/java/org/petmarket/message/controller/MessageController.java
> +
я би прибрав. шоб не можна собі було писати.

2024-05-13 05:17 UTC, LionnoiL commented on src/main/java/org/petmarket/message/service/MessageAccessCheckerService.java
> +    }
по суті обмеження тільки на авторизованих користувачів. тобто всі хто авторизовані можуть писати повідомлення. це коли вже видалення чи оновлення, то питанння чи давати маожливість адміну змінювати чужі повідомлення. гадаю можна прибрати з запиту author_id та брати його з поточного юзера.

2024-05-13 15:55 UTC, LionnoiL approved these changes

2024-05-13 16:07 UTC, merged