Blog attributes
LionnoiL/petmarket pull request #69
Opened 2024-01-30 09:51 UTC by KovalBohdan-0

Added blog attributes endpoints and added attributes to Post response and request dtos

2024-01-30 14:20 UTC, LionnoiL requested changes
Можливо ще додати ендпоінт отримання постів по id атрибуту? Щоб реалізувати клік по чіпсам на фронті. Можливо це є, просто не знаходжу.

2024-01-30 16:45 UTC, KovalBohdan-0 commented
додав

2024-01-30 18:08 UTC, LionnoiL requested changes
немає отримання списку атрибутів для побудови чіпсів. під адміном є отримання списку атрибутів. під юзером немає. потрібно щоб також список атрибутів був доступний під не авторизованим юзером.

2024-01-30 18:48 UTC, LionnoiL requested changes

2024-01-30 18:48 UTC, LionnoiL commented on src/main/java/org/petmarket/blog/service/impl/AttributeServiceImpl.java
> +    }
В цьому методі та і в інших де є маппер з мовою ти звертаєшся до checkedLang з конжою ітараією циклу. Думаю потрібно винести отримання мови на самий початок щоб запит в базу для отримання мови був один, а не по кількості елементів в списку. Це не твій баг але бажано переробити.

2024-01-30 18:49 UTC, LionnoiL commented on src/main/java/org/petmarket/blog/service/impl/AttributeServiceImpl.java
> +    }
п.с. В цьому методі не цикл але отримання мови два раза.

2024-01-30 18:50 UTC, LionnoiL requested changes

2024-01-30 18:50 UTC, LionnoiL commented on src/main/java/org/petmarket/blog/service/impl/AttributeServiceImpl.java
> +    }
Ось наприклад список.

2024-01-30 18:55 UTC, KovalBohdan-0 commented on src/main/java/org/petmarket/blog/service/impl/AttributeServiceImpl.java
> +    }
дійсно, тупанув

2024-01-30 19:23 UTC, KovalBohdan-0 commented on src/main/java/org/petmarket/blog/service/impl/AttributeServiceImpl.java
> +    }
ще в інших місцях трохи поправив

2024-01-31 06:18 UTC, LionnoiL approved these changes

2024-01-31 10:10 UTC, merged