Add fixes, add blog endpoints
LionnoiL/petmarket pull request #8
Opened 2023-10-09 09:40 UTC by antonsablev

2023-10-09 11:54 UTC, LionnoiL requested changes
Все не перевіряв т.я. багато не працює. Також у тебе навіть не залогінений користувач може мати доступ до адмінського функціоналу.

2023-10-09 11:54 UTC, LionnoiL commented on src/main/java/org/petmarket/blog/controller/admin/CategoryAdminController.java
> +
Навищо додаеш langCode в шлях? Ми це обговорювали що post буде без параметру мови і буде додаватися мова з налаштуваннь. Так у нас завжди буде переклад потрібної мови. Що буде якщо в твоєму випадку юзер додасть en мову, а в налаштуваннях стоіть ua? Що віддамо на фронт?

2023-10-09 11:54 UTC, LionnoiL commented on src/main/java/org/petmarket/blog/entity/BlogComment.java
>      @Enumerated(EnumType.STRING)
Десь вже пропонував enum статусу коментаря винести в окремий клас тому що він буде ще використовуватися.

2023-10-09 11:54 UTC, LionnoiL commented on src/main/java/org/petmarket/blog/controller/CategoryController.java
>      }
Помилка 500. java.util.NoSuchElementException: No Translation for this lang: en
GlobalExceptionHandler також не спрацював.

2023-10-09 11:54 UTC, LionnoiL commented on src/main/java/org/petmarket/blog/mapper/CategoryMapper.java
> -
Гадаю що з маппером ти перемудрив. Поки що не дійшов до перекладу але мені здається це робиться простіше.

2023-10-09 11:54 UTC, LionnoiL commented on src/main/java/org/petmarket/blog/mapper/CategoryMapper.java
> -
Я так розумію що логіка отримання перекладу в тебе потрапила в маппер. Думаю буде краще перенести її в сервіс.

2023-10-09 11:54 UTC, LionnoiL commented on src/main/java/org/petmarket/blog/controller/CategoryController.java
> +            @PathVariable(name = "id")
java.util.NoSuchElementException: No Translation for this lang: ua 
якщо переклада немає.
у всіх методах, що працюють з перелкдами, потрібно реалізувати логіку: якщо перекладу немаю, то відправляємо мову за замовчуванню.

2023-10-09 12:21 UTC, antonsablev commented on src/main/java/org/petmarket/blog/entity/BlogComment.java
>      @Enumerated(EnumType.STRING)
Справа в тому що статуси різні завжди. Ти пропонуеш зробити енум з усіма статусами для усього?

2023-10-09 12:23 UTC, antonsablev commented on src/main/java/org/petmarket/blog/controller/CategoryController.java
>      }
Короче NoSuchElement тому що катогрія є а перекладу виходить нема. Я це бачив, забув дописати перевірку.

2023-10-09 12:25 UTC, LionnoiL commented on src/main/java/org/petmarket/blog/entity/BlogComment.java
>      @Enumerated(EnumType.STRING)
Статус коментаря. У нас коментарі є що до породи і ще до чогось. Не пам'ятаю.

2023-10-09 12:28 UTC, LionnoiL commented on src/main/java/org/petmarket/blog/controller/admin/CategoryAdminController.java
> +
Прикол в тому що я додав дві категорії. В одній ua в іншій en. Тобто в кожному по одному перекладу. Що юзеру відправляти наприклад в списку категорій? Потрібно зробити механізм щоб одна мова була обов'язково. Без неї щоб взагалі сутність не зберігалася. Потім, якщо хтось забажає, він може додавати переклади. А якщо не додасть, буде виводитися мова за замовчуванню.

2023-10-09 12:29 UTC, antonsablev commented on src/main/java/org/petmarket/blog/controller/CategoryController.java
> +            @PathVariable(name = "id")
Як я вже више писав поки що треба додавати 2 переклади, тому ще нема перевіркі на відсутній перклад

Я думаю якщо нема перекладу треба щось інше відправляти якійсь warning, ато так десь пропустять переклад і на англ версіі будет суржик.

2023-10-09 12:29 UTC, LionnoiL commented on src/main/java/org/petmarket/blog/controller/admin/CategoryAdminController.java
> +
мова за замовчуванню в скрипті ініціалізації. контроллера отримання налаштувань сайту поки немає.

2023-10-09 12:30 UTC, antonsablev commented
По поводу користувача я спеціально додав у список єндпоінтів урли щоб не логінистись, а як завершу з блогом то зроблю тілкі для залогінених користувачів

2023-10-09 12:35 UTC, LionnoiL commented on src/main/java/org/petmarket/blog/controller/CategoryController.java
> +            @PathVariable(name = "id")
Нам не підходить така логіка. Ти просто не був ще на обговоренні цього. Приведу приклад: юзер створює оголошення. Йому що потрібно одразу два переклади? Ні. Хто хоче додасть. Більшість не захоче. Тому буде один переклад. Робити логіку для оголошень одну, а для всього іншого другу я думає не потрібно. Давай зробимо однаково. 
Ще проблема вилізе якщо завтра у нас додадуть третю мову. Що буде зі старими записами? В них залишиться тільки два переклади. Як це буде працювати?

2023-10-09 12:37 UTC, antonsablev commented on src/main/java/org/petmarket/blog/entity/BlogComment.java
>      @Enumerated(EnumType.STRING)
Маю наувазі що для блогКоменту це PENDING, APPROVED, SPAM
для поста це DRAFT, PUBLISHED
Для оголошень ACTIVE, NO_ACTIVE, DRAFT і тд

2023-10-09 12:47 UTC, LionnoiL commented on src/main/java/org/petmarket/blog/entity/BlogComment.java
>      @Enumerated(EnumType.STRING)
Не status в оголошенні. Статус оголошення ACTIVE, NO_ACTIVE, DRAFT. В оголошенні немає коментаря. Там є відгуки. Статус поста також ти плутаєш з статусом коментаря.
У нас є коментарі: до породи тварини та до статі блогу. CommentStatus (PENDING, APPROVED, SPAM). 
Якщо не знайдеш де це, пропоную зідзвонитися (тільки якщо сьогодні, то після 20-00). Так буде простіше.

2023-10-10 11:39 UTC, LionnoiL requested changes
Все не дивився тому що при старті вже багато недоліків.

2023-10-10 11:39 UTC, LionnoiL commented on src/main/java/org/petmarket/blog/dto/category/BlogPostCategoryResponseDto.java
>  }
BlogPostCategoryResponseDto містить все переклади. Варіант де віддавали title, description вже потрібної мови був краще.

2023-10-10 11:39 UTC, LionnoiL commented on src/main/java/org/petmarket/blog/controller/admin/CategoryAdminController.java
> +
це додавання мови чи оновлення? по назві методу контроллеру - додавання мови. а в сервісі - оновлення. 
в будь якому випадку тут баг: якщо оновлювати існуюючий переклад, він не оновлюється, а додається ще. 
![image](https://github.com/LionnoiL/petmarket/assets/21245131/b1b7127a-9153-48cb-adc9-90abbb70bbf3)

2023-10-10 11:39 UTC, LionnoiL commented on src/main/java/org/petmarket/blog/controller/CategoryController.java
> +        return categoryService.getAll(pageable, langCode);
запит по ua отримаємо все що є
![image](https://github.com/LionnoiL/petmarket/assets/21245131/0865cb5a-53ab-4c7e-9a62-f0ab3593c105)

2023-10-20 11:27 UTC, LionnoiL requested changes
Пока это все.

2023-10-20 11:27 UTC, LionnoiL commented on src/main/java/org/petmarket/blog/controller/BlogPostController.java
> +
Тут нет  @Tag

2023-10-20 11:27 UTC, LionnoiL commented on src/main/java/org/petmarket/blog/controller/CommentController.java
> +    @PreAuthorize("hasAnyRole('USER', 'ADMIN')")
@PreAuthorize("isAuthenticated()") не подойдет лучше?

2023-10-20 11:27 UTC, LionnoiL commented on src/main/java/org/petmarket/blog/controller/CommentController.java
> +            @ApiResponse(responseCode = "500", description = "Internal server error")
а если пост не найден какой статус?

2023-10-20 11:27 UTC, LionnoiL commented on src/main/java/org/petmarket/blog/controller/admin/CommentAdminController.java
> +    }
ошибка 500

2023-10-20 11:27 UTC, LionnoiL commented on src/main/java/org/petmarket/blog/dto/comment/BlogPostCommentResponse.java
> +    private CommentStatus status;
может еще добавить userId и его имя фамилию и имя?

2023-10-20 11:27 UTC, LionnoiL commented on src/main/java/org/petmarket/blog/controller/admin/BlogPostAdminController.java
> +                                            @PathVariable String status) {
Почему тип статуса String. Вообще не вижу класса PostStatus.

2023-10-20 11:27 UTC, LionnoiL commented on src/main/java/org/petmarket/blog/controller/admin/BlogPostAdminController.java
> +                                            @PathVariable Long postId,
Думаю удобнее будет сделать ендпоинт в который можно передать список id статей, а не по одной.

2023-10-20 11:27 UTC, LionnoiL commented on src/main/java/org/petmarket/blog/controller/admin/BlogPostAdminController.java
> +    @PostMapping("/{postId}/{langCode}")
В этом контроллере и в комментариях ты в параметрах пишеш название переменной типа postId или commentId, а в категориях и во всех моих просто id. Давай прийдем к одному виду или так или так.

2023-10-20 11:27 UTC, LionnoiL commented on src/main/java/org/petmarket/blog/controller/admin/BlogPostAdminController.java
> +    @PostMapping("/{postId}/{langCode}")
Название и описание в Tag контроллеров тоже у нас разные. Бросается в глаза.

2023-10-20 11:52 UTC, antonsablev commented on src/main/java/org/petmarket/blog/controller/admin/CategoryAdminController.java
> +    @PreAuthorize("hasRole('ADMIN')")
Согласен, тут тупанул

2023-10-20 11:53 UTC, antonsablev commented on src/main/java/org/petmarket/blog/dto/category/BlogPostCategoryResponseDto.java
> +    private List<CategoryTranslationDto> translations;
Смысл только в том чтоб не мапить вручную перевод
Маппер у меня сам все мапит, а отдавать в таком виде я проблемы не вижу, как минимум мы так с постом отдаем коммпентирии и категории, чего не отдавать так и переводы?

2023-10-20 11:55 UTC, antonsablev commented on src/main/java/org/petmarket/blog/controller/admin/CategoryAdminController.java
> +    }
Тут не вижу тоже проблемы? Ты предлагаеш передавать первод в метод который апдейтит запись?

2023-10-20 11:58 UTC, antonsablev commented on src/main/java/org/petmarket/blog/controller/admin/CategoryAdminController.java
> +@Tag(name = "Admin Blog Categories Management", description = "Endpoints for managing blog categories by admin")
Понял, исправлю сейчас

2023-10-20 12:00 UTC, antonsablev commented on src/main/java/org/petmarket/language/repository/LanguageRepository.java
>  }
Поправил, спасибо

2023-10-20 12:01 UTC, antonsablev commented on src/main/java/org/petmarket/blog/service/impl/CategoryServiceImpl.java
>      }
Да я переключил на твой метод в репозитории

2023-10-20 12:01 UTC, antonsablev commented on src/main/java/org/petmarket/blog/controller/BlogPostController.java
> +
Спасибо Добавил

2023-10-20 12:02 UTC, antonsablev commented on src/main/java/org/petmarket/blog/controller/CommentController.java
> +    @PreAuthorize("hasAnyRole('USER', 'ADMIN')")
Не знал про такой тег, поменял на него , спасибо

2023-10-20 13:23 UTC, antonsablev commented on src/main/java/org/petmarket/blog/controller/admin/BlogPostAdminController.java
> +                                            @PathVariable String status) {
Пост статус в сервисе в методе апдейт

    @Override
    public BlogPostResponseDto updateStatus(Long postId, String status) {
        Post post = findById(postId);
        post.setStatus(Post.Status.valueOf(status));
        postRepository.save(post);
        return postMapper.toDto(post);
    }

2023-10-20 13:29 UTC, antonsablev commented on src/main/java/org/petmarket/blog/controller/admin/BlogPostAdminController.java
> +    @PostMapping("/{postId}/{langCode}")
Поменял на postId и поправил Tag

2023-10-20 13:38 UTC, antonsablev commented on src/main/java/org/petmarket/blog/controller/admin/CommentAdminController.java
> +    }
В общем в постмане работает а в свагере есть такой момент
{
  "page": 0,
  "size": 1,
  "sort": [
    "string"
  ]
}
идея ругается на string 
в свагере надо подставлять ASC илил DECS вместо стринг

чтоб было вот так

{
  "page": 0,
  "size": 1,
  "sort": "ASC"
}

с одной стороны логично что запрос должен быть правильный
С другой странно как то свагер подставил значение
сейчас убрал pageable для категорий

2023-10-20 13:45 UTC, antonsablev commented on src/main/java/org/petmarket/blog/dto/comment/BlogPostCommentResponse.java
> +    private CommentStatus status;
Добавил

2023-10-20 14:20 UTC, antonsablev commented on src/main/java/org/petmarket/blog/controller/admin/BlogPostAdminController.java
> +                                            @PathVariable Long postId,
C постами думаю нет смысла делать список, но идея хорошая для комментариев, их реально легче списком принимать и менять им статус массово. 
Передалал на комментариях.
Спасибо

2023-10-20 14:35 UTC, LionnoiL commented on src/main/java/org/petmarket/blog/controller/admin/BlogPostAdminController.java
> +                                            @PathVariable String status) {
можно такpublic BlogPostResponseDto updateStatus(Long postId, Post.Status status) {

2023-10-20 14:39 UTC, LionnoiL commented on src/main/java/org/petmarket/blog/dto/category/BlogPostCategoryResponseDto.java
> +    private List<CategoryTranslationDto> translations;
В твоем варианте респонс сложно выглядит.

2023-10-20 14:47 UTC, LionnoiL commented on src/main/java/org/petmarket/blog/controller/admin/CategoryAdminController.java
> +    }
Да. Я делал просто в апдейте. Если есть перевод, он обновляется. Если нет, добавляется.

2023-10-20 16:13 UTC, LionnoiL requested changes

2023-10-20 16:13 UTC, LionnoiL commented on src/main/java/org/petmarket/blog/controller/admin/CommentAdminController.java
> +    }
Попробуй все таки сделать

@PutMapping("/{commentsIds}/updateStatus")
 public List<BlogPostCommentResponse> changeCommentStatus(
            @PathVariable List<Long> commentsIds,
            @RequestParam CommentStatus status)

Посмотри как это будет выглядеть в свагере.

2023-10-20 16:42 UTC, antonsablev commented on src/main/java/org/petmarket/blog/dto/posts/BlogPostResponseDto.java
> +
Тут думаю что не нужно, эта информация в блог посте не нужна

2023-10-20 16:49 UTC, antonsablev commented on src/main/java/org/petmarket/blog/controller/CommentController.java
> +            @ApiResponse(responseCode = "404", description = "Comment not found"),
точно

2023-10-20 16:49 UTC, antonsablev commented on src/main/java/org/petmarket/blog/controller/BlogPostController.java
> +    }
Делаю

2023-10-20 16:49 UTC, antonsablev commented on src/main/java/org/petmarket/blog/controller/BlogPostController.java
> +        return postService.getAllByCategory(langCode, categoryId);
Делаю

2023-10-20 16:58 UTC, antonsablev commented on src/main/java/org/petmarket/blog/controller/admin/CategoryAdminController.java
> +    }
Да это не предусмотрел Согласен

2023-10-20 17:00 UTC, antonsablev commented on src/main/java/org/petmarket/blog/dto/posts/BlogPostResponseDto.java
> +
Может заменим просто username на Имя и Фамилию?

2023-10-20 17:07 UTC, antonsablev commented on src/main/java/org/petmarket/blog/controller/admin/CommentAdminController.java
> +    }
Тут не совсем понимаю зачем

2023-10-20 17:08 UTC, LionnoiL commented on src/main/java/org/petmarket/blog/dto/posts/BlogPostResponseDto.java
> +
Можно. Просто у тебя выводится почта автора. Не понятно зачем это нужно на фронте. Если это будет использоваться в админке, то лучше выводить подробную информацию об авторе.

2023-10-20 17:10 UTC, LionnoiL commented on src/main/java/org/petmarket/blog/controller/admin/CommentAdminController.java
> +    }
![image](https://github.com/LionnoiL/petmarket/assets/21245131/6f53eaeb-14b8-4826-adce-249abd7342b5)

2023-10-20 17:11 UTC, LionnoiL commented on src/main/java/org/petmarket/blog/controller/admin/CommentAdminController.java
> +    }
затем что видно какие есть значения. и в принципе легче сам запрос писать.

2023-10-20 17:14 UTC, LionnoiL commented on src/main/java/org/petmarket/blog/controller/admin/CommentAdminController.java
> +    }
![image](https://github.com/LionnoiL/petmarket/assets/21245131/2305c49b-0777-43a3-a36a-3b148fa2a60d)

2023-10-21 07:02 UTC, antonsablev commented on src/main/java/org/petmarket/blog/service/impl/PostServiceImpl.java
> +        post.setUpdated(LocalDateTime.now());
Добавил спасибо,

2023-10-21 07:16 UTC, antonsablev commented on src/main/java/org/petmarket/blog/controller/admin/CategoryAdminController.java
> +    }
добавил проверку
спасибо

2023-10-21 07:19 UTC, antonsablev commented on src/main/java/org/petmarket/blog/dto/posts/BlogPostResponseDto.java
> +
добавил

2023-10-21 07:42 UTC, antonsablev commented on src/main/java/org/petmarket/blog/service/impl/PostServiceImpl.java
> +    }
Да согласен
Я переделал 
чат gpt помог с запросом.

2023-10-21 08:21 UTC, antonsablev commented on src/main/java/org/petmarket/blog/controller/admin/CommentAdminController.java
> +    }
Я добавил, но честно говоря свагером не пользуюсь я пользуюсь в основном постманом, если тебе так удобней ок не проблема

2023-10-21 08:31 UTC, LionnoiL commented on src/main/java/org/petmarket/blog/controller/admin/CommentAdminController.java
> +    }
Не мне так удобнее. Свагер будут смотреть тестировщики и фронтенд.

2023-10-21 08:44 UTC, LionnoiL approved these changes

2023-10-21 08:54 UTC, merged