79 Додаткові телефони в юзері
LionnoiL/petmarket pull request #85
Opened 2024-03-08 07:00 UTC by LionnoiL

Перероблено з одного номеру телефону на список номерів. Доданий реквізит mainPhone. Додана перевірка на доступ до повної інформації юзера. Доступ мають тільки адміністратори або сам юзер до себе.

2024-03-08 19:11 UTC, KovalBohdan-0 approved these changes
А добавляння номеру, будемо робити разом з іншими додатковими параметрами чи воно є?

2024-03-08 19:28 UTC, KovalBohdan-0 requested changes
При добавлянні нового юзера видає 500 error

2024-03-09 08:26 UTC, LionnoiL commented
виправив помилку при додаванні нового юзера. додавання номерів будуть разом з оновленням користувача. це буде окремою таскою.

2024-03-09 12:19 UTC, KovalBohdan-0 approved these changes

2024-03-09 14:16 UTC, merged